name: "\U0001F41B Bug Report"
description: Report a general library issue.
labels: [bug]
body:
- type: input
  attributes:
    label: Package version
    description: "Please provide the full version of meema-client-php that you're experiencing the bug with."
    placeholder: "v1.2.3"
  validations:
    required: true
- type: input
  attributes:
    label: PHP version
    description: "Please provide the full version of PHP that you're experiencing the bug with."
    placeholder: "v8.0.3"
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
    description: "Please describe what is happening and what you expect to happen."
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: "Please provide accurate steps to reproduce the bug."
  validations:
    required: true
